[supervisord]
nodaemon=true

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/uvicorn.err.log
stdout_logfile=/var/log/uvicorn.out.log

[program:celery-worker]
command=celery -A app.celery_app worker --pool=solo --loglevel=info
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/celery-worker.err.log
stdout_logfile=/var/log/celery-worker.out.log

[program:celery-beat]
command=celery -A app.celery_app beat --loglevel=info
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/celery-beat.err.log
stdout_logfile=/var/log/celery-beat.out.log
