apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: crm
data:
  APP_BASE_URL: "https://crm.ecogo.ai/"
  APP_DB_HOSTNAME: "mysql.infra.svc.cluster.local"
  APP_DB_NAME: "u774665502_crm_ecogo"
