apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-app-ingress
  namespace: crm
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - crm.ecogo.ai
      secretName: crm-tls
  rules:
    - host: crm.ecogo.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crm-app
                port:
                  number: 80
