apiVersion: v1
kind: Secret
metadata:
  name: crm-secret
  namespace: crm
type: Opaque
stringData:
  APP_ENC_KEY: "212e5d9fa9707f94b9a1b0636747bd1b"
  # Using the root password for initial migration if needed, or app_user
  APP_DB_USERNAME: "app_user"
  APP_DB_PASSWORD: "App@12345!"
