apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: infra
type: Opaque
data:
  # Replace 'postgres' below with your desired password, base64 encoded
  postgres-password: postgres