apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: infra
type: Opaque
stringData:
  # Matching the password used in authentication and configuration-b2c configmaps
  postgres-password: "Net*admin578"