apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-mysql-0
  namespace: infra
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem