apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-service-env
  namespace: refundai
data:
  DB_USER: "currency_user"
  DB_PASSWORD: "Net*admin578"
  #DB_PASSWORD1: "KldkhhmS#392"
  DB_HOST: "mysql.infra.svc.cluster.local"
  DB_NAME: "currency_conversion_service"
  DB_PORT: "3306"

  # Kafka
  KAFKA_BROKER_URL: "kafka-service.infra.svc.cluster.local:9092"
  KAFKA_TOPIC: "gst_logging"
  KAFKA_USERNAME: ""
  KAFKA_PASSWORD: ""

  # Redis
  REDIS_USERNAME: "default"
  REDIS_HOST: "redis-master.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "RedisPassword123!"
  REDIS_DB: "2"
