apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  namespace: infra
  labels:
    app: nats
spec:
  ports:
    - name: client
      port: 4222
    - name: cluster
      port: 6222
    - name: monitor
      port: 8222
  clusterIP: None
  selector:
    app: nats
