apiVersion: v1
kind: Service
metadata:
  name: nats-client
  namespace: infra
  labels:
    app: nats
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 4222
      targetPort: 4222
  selector:
    app: nats
