apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-backups-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 50Gi
