apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: seateleven-routes
  namespace: travoze
spec:
  http:
    - name: aggregator
      match:
        paths:
          - "/api/aggregator/*"
      backends:
        - serviceName: aggregator
          servicePort: 8081
