apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: infra
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: zookeeper-storage
      volumes:
      - name: zookeeper-storage
        persistentVolumeClaim:
          claimName: zookeeper-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30