apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: travoze
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      logging:
        verbosity: detailed # Updated from deprecated 'loglevel: debug' for newer OTel versions
      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
