apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: infra
type: Opaque
stringData:
  CLICKHOUSE_USER: admin
  CLICKHOUSE_PASSWORD: ClickHousePassword123!
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
