apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: server
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-08-28T10:07:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: postgres
    name: postgres-data-postgres-0
    namespace: default
    resourceVersion: "19806"
    uid: e80487c2-3f7f-4a8e-8693-4a0e51c278f1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-e80487c2-3f7f-4a8e-8693-4a0e51c278f1
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: server
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-08-28T10:44:12Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: postgres
    name: postgres-data-postgres-1
    namespace: default
    resourceVersion: "24016"
    uid: 580e3c6f-b288-40c2-883f-8cbdfe387cfc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-580e3c6f-b288-40c2-883f-8cbdfe387cfc
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: server
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-08-28T10:44:22Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: postgres
    name: postgres-data-postgres-2
    namespace: infra
    resourceVersion: "24086"
    uid: f270e156-3462-4255-b255-ad9131e2133c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-f270e156-3462-4255-b255-ad9131e2133c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""